const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const enc=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o))));
const dec=s=>JSON.parse(decodeURIComponent(escape(atob(s))));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

const [config,days]=await Promise.all([fetch('config.json?v=6').then(r=>r.json()),fetch('days.json?v=6').then(r=>r.json())]);
const STORE='intre-noi-final-v6';
const blank={profile:null,answers:{},steps:{},completed:{},otherDone:{},photos:{},tomorrow:[],openedMusic:{},sealed:{}};
let state={...blank,...JSON.parse(localStorage.getItem(STORE)||'{}')};
let profile=state.profile,currentDay=null,stage=0,view='today',selected=[],photoData='';

const extra={
1:{story:'Nu începem prin promisiuni mari. Începem printr-un pas mic, sincer și făcut astăzi.',build:'Scrie un lucru foarte concret prin care vei fi prezent(ă) astăzi, nu când veți locui împreună.',teaser:'Mâine vei vedea lumea prin ochii celuilalt.'},
2:{story:'Parisul și Mentonul nu arată la fel. Tocmai de aceea astăzi vă împrumutați privirea unul altuia.',build:'Alege un moment al zilei și trimite fotografia cu o explicație scurtă: de ce ai ales tocmai acel cadru?',teaser:'Mâine nu veți vorbi doar despre ce ați făcut, ci despre cum sunteți cu adevărat.'},
3:{story:'Uneori spunem „sunt bine” ca să nu complicăm ziua celuilalt. Astăzi alegem adevărul spus cu blândețe.',build:'Spune exact ce fel de sprijin ai nevoie și ce nu ai nevoie. Celălalt nu trebuie să ghicească.',teaser:'Mâine exersăm unul dintre cele mai rare daruri: să ascultăm fără să ne apărăm.'},
4:{story:'A asculta nu înseamnă să aștepți pauza ca să răspunzi. Înseamnă să intri, pentru o clipă, în lumea celuilalt.',build:'După mesajul vocal al celuilalt, răspunde mai întâi cu „Am înțeles că...” și abia apoi spune ce simți tu.',teaser:'Mâine deschidem o ușă spre lucrurile pe care le purtăm în tăcere.'},
5:{story:'O relație pentru toată viața începe când două persoane învață să nu lase una singură tot ce este greu.',build:'Alege un lucru pe care îl poți împărți deja: o grijă, o decizie, o rugăciune sau o responsabilitate.',teaser:'Mâine este ziua postului: nu o performanță, ci o întâlnire sinceră cu Dumnezeu și unul cu altul.'},
6:{story:'Postul nu este un concurs de rezistență. Este o zi în care încetinim, spunem adevărul despre starea noastră și alegem să ne purtăm în rugăciune.',build:'Stabiliți împreună dacă postiți, până când, cum vă verificați starea și ce faceți dacă unul nu se simte bine.',teaser:'Mâine luați cu voi din biserică nu doar o idee, ci un pas de trăit.'},
7:{story:'Duminica nu rămâne doar în biserică. Ceea ce auzim devine felul în care vorbim, iertăm și iubim.',build:'Alege o idee din predică și transform-o într-un gest pentru relația voastră în următoarele 24 de ore.',teaser:'Mâine vorbiți despre acel „acasă” care nu este o adresă.'},
8:{story:'Acasă poate fi o voce, o privire, liniștea de a nu te apăra și siguranța că nu vei fi abandonat la primul obstacol.',build:'Creează astăzi pentru celălalt un moment de „acasă”: o voce calmă, un mesaj, timp sau o rugăciune.',teaser:'Mâine înlocuim „cândva” cu o zi, o oră și un gest real.'},
9:{story:'Viitorul nu se construiește din „o să fac”. Se construiește din obiceiuri mici repetate înainte să fie comod.',build:'Alege un obicei pentru șapte zile, spune ora sau contextul în care îl faci și cum vei ști că l-ai respectat.',teaser:'Mâine priviți același cer și puneți un pas sub o dorință.'},
10:{story:'Sub același cer, distanța se micșorează pentru câteva clipe. Dar o dorință devine serioasă doar când primește și un pas.',build:'Pentru dorința ta, scrie un pas pe care îl poți face în următoarele șapte zile.',teaser:'Mâine decideți cum vreți să rămâneți de aceeași parte chiar și când vă doare.'},
11:{story:'Într-o relație lungă nu întrebarea este dacă vor exista conflicte, ci dacă veți lupta unul împotriva celuilalt sau împreună împotriva problemei.',build:'Formulați o regulă simplă de conflict și păstrați-o ca regulă comună.',teaser:'Mâine descoperiți prin ce gesturi se simte iubirea, nu doar cum se numește.'},
12:{story:'Uneori iubim sincer, dar într-o limbă pe care celălalt nu o aude bine. Astăzi traduceți iubirea în gesturi concrete.',build:'Alege două gesturi ușor de repetat și spune cât de des ți-ar face bine.',teaser:'Mâine este al doilea post: privim ce a schimbat Dumnezeu, nu doar ce am cerut.'},
13:{story:'Al doilea post nu repetă primul. El întreabă: ce s-a mișcat în inimă, ce a rămas greu și unde avem nevoie de har?',build:'Stabiliți din nou forma postului și un moment în care vă întrebați sincer: „Cum ești acum?”',teaser:'Mâine Alina se întoarce. Alegeți ce nu vreți să pierdeți când revine rutina.'},
14:{story:'Drumul de întoarcere nu închide povestea. El verifică ce obiceiuri și ce adevăruri luați cu voi în viața normală.',build:'Alege trei lucruri din aceste zile și spune cum le păstrați după vacanță.',teaser:'Mâine este prima zi de lucru după vacanță și ultimul capitol al acestui drum.'},
15:{story:'Finalul nu întreabă dacă a fost frumos. Întreabă cine ați devenit și ce alegeți să continuați.',build:'Scrie un angajament de 30 de zile: mic, măsurabil, realist și făcut cu Dumnezeu.',teaser:'Nu mai așteptăm următoarea pagină. Începem s-o trăim.'}
};
for(const d of days) Object.assign(d,extra[d.id]||{});
const spotify={
'Scopul Meu':'https://open.spotify.com/search/Scopul%20Meu%20Alin%20Emima%20Timofte',
'Pentru tine':'https://open.spotify.com/search/Ramona%20Hanganu%20Pentru%20tine',
'I Prayed for You':'https://www.youtube.com/results?search_query=I+Prayed+for+You+Christian+Wedding+Song+Faithful+Love+Story+Duet'
};

function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function dateParis(add=0){const now=new Date(Date.now()+add*864e5);return new Intl.DateTimeFormat('en-CA',{timeZone:config.timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
function indexToday(){const d=dateParis();const i=days.findIndex(x=>x.date===d);if(i>=0)return i;return d<days[0].date?0:days.length-1}
function available(d){return d.date<=dateParis()}
function current(){const unlocked=days.filter(available);return unlocked.at(-1)||days[0]}
function me(){return config.people[profile]||null}
function otherKey(){return profile==='alina'?'eugeniu':'alina'}
function other(){return config.people[otherKey()]}

function init(){importHash();bindGlobal();if(!profile)chooseProfile();else openToday()}
function bindGlobal(){
 $('#profileBtn').onclick=chooseProfile;$('#homeBtn').onclick=openToday;$('#closeDialog').onclick=()=>$('#dialog').close();
 $$('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
}
function chooseProfile(){
 $('#dialogBody').innerHTML=`<div class="kicker">POVESTEA ESTE PENTRU DOI</div><h2>Cine ești astăzi?</h2><p>Alegerea rămâne pe telefonul acesta.</p><div class="choices"><button class="choice" data-profile="alina">🦋 Sunt Alina · Menton</button><button class="choice" data-profile="eugeniu">❤️ Sunt Eugeniu · Paris</button></div>`;
 $('#dialog').showModal();$$('[data-profile]').forEach(b=>b.onclick=()=>{profile=b.dataset.profile;state.profile=profile;save();$('#dialog').close();openToday()})
}
function switchView(v){view=v;$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='today')openToday();if(v==='journey')renderJourney();if(v==='album')renderAlbum();if(v==='tomorrow')renderTomorrow()}
function openToday(){view='today';$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view==='today'));currentDay=current();stage=state.steps[currentDay.id]||0;photoData=state.photos[currentDay.id]||'';renderHero();renderChapter()}

function renderHero(advance=0){const d=currentDay||current();const completed=Object.keys(state.completed).filter(k=>state.completed[k]).length;const progress=Math.max(1,Math.min(15,d.id+advance));const t=(progress-1)/14;const x=90+720*t,y=205-85*Math.sin(Math.PI*t)+20*Math.sin(3*Math.PI*t);const pathLen=860,done=pathLen*t;$('#profileBtn').textContent=me()?`${me().emoji} ${me().name}`:'Alege profilul';
 $('#hero').innerHTML=`<div class="route-card"><div class="route-art"><div class="sun"></div><div class="cloud c1">☁️</div><div class="cloud c2">☁️</div><svg class="route-svg" viewBox="0 0 900 310" aria-label="Drumul Paris Menton"><path class="route-path" d="M90 220 C210 65 340 245 470 130 C590 25 690 190 810 95"/><path class="route-done" d="M90 220 C210 65 340 245 470 130 C590 25 690 190 810 95" pathLength="860" stroke-dasharray="${done} ${pathLen-done}"/><text x="55" y="258" class="landmark">🗼</text><text x="43" y="288" class="city-label">Paris · Eugeniu</text><text x="430" y="245" class="landmark">🏔️</text><text x="790" y="125" class="landmark">🌴</text><text x="742" y="67" class="city-label">Menton · Alina</text><text x="${x}" y="${y}" class="route-heart">❤️</text></svg><div class="water"></div></div><div class="route-copy"><div class="kicker">DRUMUL NOSTRU</div><h1>${d.id===15?'Nu este un final. Este o alegere.':`Ziua ${d.id}: încă un pas spre noi`}</h1><p>${d.story}</p><div class="progress">${days.map(x=>`<i class="${x.id<=progress?'done':''}"></i>`).join('')}</div><div class="progress-note"><span class="pill">${completed}/15 zile sigilate</span><span class="pill">${me()?.name||'—'} · ${me()?.city||'—'}</span><span class="pill">${Math.max(0,15-progress)} pași rămași</span></div></div></div>`
}

function renderChapter(){const d=currentDay;const labels=['Deschide','Muzică','Gest','Întrebare','Construim','Rugăciune','Sigiliu'];$('#app').innerHTML=`<article class="chapter"><header class="chapter-head"><div class="kicker">CAPITOLUL ${d.id}</div><div class="chapter-icon">${d.icon}</div><h2>${d.title}</h2><p>${d.story}</p></header><div class="step-map">${labels.map((l,i)=>`${i?'<span></span>':''}<button class="${i<stage?'done':i===stage?'current':''}" data-step="${i}" title="${l}">${i<stage?'✓':i+1}</button>`).join('')}</div><div class="stage" id="stage"></div></article>`;$$('[data-step]').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;if(n<=stage){stage=n;renderStage()}});renderStage()}
function advance(){stage=Math.min(6,stage+1);state.steps[currentDay.id]=Math.max(state.steps[currentDay.id]||0,stage);save();renderChapter();scrollTo({top:$('#app').offsetTop-92,behavior:'smooth'})}
function card(title,html,intro=''){return `<div class="stage-card">${intro?`<div class="stage-intro">${intro}</div>`:''}<h3>${title}</h3>${html}</div>`}
function answer(){return state.answers[currentDay.id]||{}}
function setAns(k,v){state.answers[currentDay.id]={...answer(),[k]:v};save()}
function renderStage(){selected=(answer().selected||[]).slice();photoData=state.photos[currentDay.id]||'';const d=currentDay,root=$('#stage');
 if(stage===0)root.innerHTML=card('Deschide ziua',`${receivedLetter()}<p>Astăzi nu încercăm să fim perfecți. Încercăm să fim sinceri, atenți și prezenți.</p><button class="primary" id="go">Deschide capitolul</button>`,'<b>Un pas mic făcut astăzi valorează mai mult decât o promisiune mare pentru „cândva”.</b>');
 if(stage===1)root.innerHTML=card('Ascultă și lasă cuvintele să ajungă la tine',`<a class="song-card" href="${d.song.url}" target="_blank" rel="noopener"><span class="vinyl">♥</span><span><small>Melodia capitolului</small><b>${esc(d.song.title)}</b><small>${esc(d.song.artist)}</small></span><em>▶</em></a><div class="music-actions"><a href="${spotify[d.song.title]||d.song.url}" target="_blank" rel="noopener">Deschide melodia</a><button id="heard">Am ascultat-o ❤️</button></div><p>Nu trebuie să ascultați în același minut. Important este ca fiecare să intre în zi cu aceeași melodie și să aleagă un vers sau o idee care l-a atins.</p><textarea id="musicNote" class="textarea" placeholder="Ce cuvânt sau ce idee din melodie a rămas cu tine?">${esc(answer().music||'')}</textarea>`);
 if(stage===2)root.innerHTML=card('Un gest real, astăzi',`<p><b>${esc(d.action)}</b></p><p>${esc(d.build)}</p>${d.photo?photoUI(d.photo):''}<textarea id="actionText" class="textarea" placeholder="Ce fac concret, când și cum?">${esc(answer().action||'')}</textarea><button class="primary" id="saveAction">Am ales gestul și momentul</button>`,'<b>Nu „după vacanță”. Nu „când vom locui împreună”. Astăzi.</b>');
 if(stage===3)root.innerHTML=card('Cunoaște-mă mai bine',`<p><b>${esc(d.question)}</b></p>${d.options?.length?`<div class="choices">${d.options.map(o=>`<button class="choice ${selected.includes(o)?'selected':''}" data-choice="${esc(o)}">${esc(o)}</button>`).join('')}</div>`:''}<textarea id="answerText" class="textarea" placeholder="Scrie sincer. Nu există răspunsul perfect.">${esc(answer().text||'')}</textarea><button class="primary" id="saveAnswer">Păstrează răspunsul</button>`);
 if(stage===4)root.innerHTML=card('Transformăm răspunsul într-un pas',`<p>${esc(d.build)}</p><textarea id="buildText" class="textarea" placeholder="Pasul meu: ce fac, când îl fac și cum vei putea observa?">${esc(answer().build||'')}</textarea><button class="primary" id="saveBuild">Îmi asum pasul acesta</button>`,'<b>O relație pentru o viață se construiește din lucruri care pot fi văzute, nu doar auzite.</b>');
 if(stage===5)root.innerHTML=card('Trei motive de rugăciune',`${fastingBlock(d)}<p>Scrieți și starea, și nevoia, și felul în care celălalt poate susține.</p><div class="prayers">${d.prayer.map((p,i)=>`<div class="prayer-row"><b>${i+1}. ${esc(p)}</b><textarea class="textarea" data-prayer="${i}" placeholder="Cum mă simt? Ce cer lui Dumnezeu? Cum mă poți susține?">${esc(answer().prayers?.[i]||'')}</textarea></div>`).join('')}</div><button class="primary" id="savePrayer">Păstrează motivele noastre</button>`);
 if(stage===6)root.innerHTML=sealScreen();bindStage()}
function bindStage(){
 $('#go')?.addEventListener('click',advance);
 $('#heard')?.addEventListener('click',()=>{setAns('music',$('#musicNote').value.trim()||'Am ascultat melodia.');state.openedMusic[currentDay.id]=true;save();advance()});
 $('#saveAction')?.addEventListener('click',()=>{const v=$('#actionText').value.trim();if(!v)return alert('Scrie cum vei face gestul.');setAns('action',v);advance()});
 $$('[data-choice]').forEach(b=>b.onclick=()=>{const v=b.dataset.choice;selected=selected.includes(v)?selected.filter(x=>x!==v):[...selected,v];b.classList.toggle('selected')});
 $('#saveAnswer')?.addEventListener('click',()=>{const text=$('#answerText').value.trim();if(!text&&!selected.length)return alert('Alege sau scrie un răspuns.');state.answers[currentDay.id]={...answer(),selected,text};save();advance()});
 $('#saveBuild')?.addEventListener('click',()=>{const v=$('#buildText').value.trim();if(!v)return alert('Scrie pasul concret.');setAns('build',v);advance()});
 $('#savePrayer')?.addEventListener('click',()=>{const ps=$$('[data-prayer]').map(x=>x.value.trim());if(ps.some(x=>!x))return alert('Completați cele trei motive.');state.answers[currentDay.id]={...answer(),prayers:ps,fast:$('#fastChoice')?.value||''};save();advance()});
 $('#photoInput')?.addEventListener('change',handlePhoto);$('#sealBtn')?.addEventListener('click',animateSeal);$('#shareResult')?.addEventListener('click',shareResult);$('#shareHeart')?.addEventListener('click',shareHeart);$('#tomorrowQuick')?.addEventListener('click',()=>switchView('tomorrow'))
}
function fastingBlock(d){if(![6,13].includes(d.id))return '';return `<div class="notice"><b>Postul nostru</b><p>Înainte să începeți, întrebați-vă sincer dacă puteți și vreți să postiți. Sănătatea nu este lipsă de credință. Puteți alege post alimentar, o perioadă mai scurtă sau un timp special de rugăciune.</p><select id="fastChoice" class="textarea" style="min-height:58px"><option value="">Alege forma zilei</option><option>Postim împreună</option><option>Unul postește, celălalt susține și se roagă</option><option>Alegem o perioadă mai scurtă</option><option>Alegem rugăciune și liniște fără post alimentar</option><option>Mai întâi discutăm starea noastră</option></select></div>`}
function photoUI(label){return `<div class="photo-box"><b>📷 ${esc(label)}</b><p>Fă fotografia acum sau alege-o din telefon. Ea va apărea în rezultatul zilei și în album.</p><input id="photoInput" type="file" accept="image/*" capture="environment">${photoData?`<img class="photo-preview" src="${photoData}" alt="Fotografia zilei">`:''}</div>`}
function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{const img=new Image;img.onload=()=>{const c=document.createElement('canvas'),max=1200,scale=Math.min(1,max/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);state.photos[currentDay.id]=c.toDataURL('image/jpeg',.78);save();renderStage()};img.src=r.result};r.readAsDataURL(f)}

function summaryHTML(){const a=answer();return `<div class="letter-preview"><h4>Ziua ${currentDay.id} · ${esc(currentDay.title)}</h4><ul><li><b>Melodia:</b> ${esc(a.music||'ascultată')}</li><li><b>Gestul:</b> ${esc(a.action||'—')}</li><li><b>Răspunsul:</b> ${esc([...(a.selected||[]),a.text].filter(Boolean).join(' · ')||'—')}</li><li><b>Pasul concret:</b> ${esc(a.build||'—')}</li><li><b>Rugăciunea:</b> ${(a.prayers||[]).filter(Boolean).length}/3 motive</li></ul></div>`}
function sealScreen(){const mine=!!state.completed[currentDay.id],otherDone=!!state.otherDone[currentDay.id];if(!mine)return card('Ziua este gata. Acum o păstrăm.',`${summaryHTML()}<p>Privește încă o dată ce ai scris. Apoi răspunsurile vor coborî în plic, plicul se va închide și va primi o pecete.</p><div class="closing-scene"><div class="mail-stage" id="mailStage"><div class="mail-envelope"><div class="mail-paper"><b>${me().name} ❤️ ${other().name}</b><p>Un pas real, un răspuns sincer și trei motive de rugăciune.</p></div><div class="mail-flap"></div><div class="wax">♥</div></div></div><button class="primary" id="sealBtn">Gata — sigilează ziua</button></div>`);
 return card('Plic sigilat',`<div class="closing-scene"><div class="mail-stage sealed"><div class="mail-envelope"><div class="mail-paper"><b>Ziua ${currentDay.id} este păstrată.</b><p>Răspunsul, gestul și rugăciunea au rămas în povestea voastră.</p></div><div class="mail-flap" style="transform:rotateX(180deg)"></div><div class="wax">♥</div></div></div><div class="love-message show">Te iubesc</div><div class="heart-status">${mine&&otherDone?'<div class="full-heart">❤️</div>':`<div class="half-heart left ready">❤️</div><div class="half-heart right ${otherDone?'ready':''}">❤️</div>`}</div><div class="status-copy">${otherDone?'Amândoi ați răspuns. Inima bate între Paris și Menton.':'Jumătatea ta este aprinsă. Trimite confirmarea; când celălalt o deschide, a doua jumătate se aprinde.'}</div><div class="final-map">${esc(currentDay.teaser)}</div><button class="primary" id="shareHeart">Trimite jumătatea inimii ❤️</button><button class="secondary" id="shareResult">Trimite rezultatul zilei</button><button class="secondary" id="tomorrowQuick">Lasă un plic pentru mâine ✉</button></div>`)}
function animateSeal(){const s=$('#mailStage');s.classList.add('sealing');$('#sealBtn').disabled=true;setTimeout(()=>{state.completed[currentDay.id]=true;state.sealed[currentDay.id]=Date.now();save();renderHero(1);renderStage()},2100)}

function receivedLetter(){const letter=state.tomorrow.find(x=>x.openDate<=dateParis()&&!x.read);if(!letter)return '<div class="notice">Dacă ai primit un plic de la celălalt, deschide linkul trimis. El va apărea aici la data potrivită.</div>';letter.read=true;save();return `<div class="sealed-letter"><b>💌 Un plic de la ${esc(letter.fromName||'celălalt')}</b><p>${esc(letter.text)}</p></div>`}
function shareHeart(){const url=location.origin+location.pathname+'#sync='+encodeURIComponent(enc({type:'done',day:currentDay.id,from:profile}));share({title:'Jumătatea inimii mele',text:`Am terminat ziua ${currentDay.id}. Deschide linkul ca să aprinzi și jumătatea mea pe telefonul tău ❤️`,url})}
function importHash(){try{if(location.hash.startsWith('#sync=')){const x=dec(decodeURIComponent(location.hash.slice(6)));if(x.type==='done')state.otherDone[x.day]=true}else if(location.hash.startsWith('#letter=')){const x=dec(decodeURIComponent(location.hash.slice(8)));if(!state.tomorrow.some(l=>l.id===x.id))state.tomorrow.push({...x,read:false})}save();if(location.hash)history.replaceState(null,'',location.pathname)}catch(e){console.warn(e)}}
async function share(data){if(navigator.share)try{return await navigator.share(data)}catch{}const text=[data.text,data.url].filter(Boolean).join('\n');await navigator.clipboard?.writeText(text);prompt('Copiază și trimite:',text)}

async function shareResult(){const a=answer(),text=`Ziua ${currentDay.id} — ${currentDay.title}\n\n🎵 ${a.music||'-'}\n\n❤️ Gestul meu:\n${a.action||'-'}\n\n💬 Răspunsul meu:\n${[...(a.selected||[]),a.text].filter(Boolean).join(' · ')||'-'}\n\n🌱 Pasul meu concret:\n${a.build||'-'}\n\n🙏 Cele trei motive:\n${(a.prayers||[]).map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nTe iubesc ❤️`;
 const blob=await makeShareCard(text,state.photos[currentDay.id]);const file=new File([blob],`intre-noi-ziua-${currentDay.id}.jpg`,{type:'image/jpeg'});if(navigator.canShare?.({files:[file]}))try{return await navigator.share({title:`Ziua ${currentDay.id}`,text,files:[file]})}catch{}const aTag=document.createElement('a');aTag.href=URL.createObjectURL(blob);aTag.download=file.name;aTag.click();await navigator.clipboard?.writeText(text);alert('Imaginea a fost salvată, iar textul copiat. Trimite-le împreună în WhatsApp.')}
async function makeShareCard(text,photo){const c=$('#shareCanvas'),ctx=c.getContext('2d');ctx.fillStyle='#f5e5d8';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fffaf4';rounded(ctx,55,55,970,1240,48);ctx.fill();ctx.fillStyle='#a74e6c';ctx.font='bold 31px sans-serif';ctx.fillText(`ÎNTRE NOI · ZIUA ${currentDay.id}`,100,125);ctx.fillStyle='#30292f';ctx.font='bold 58px Georgia';let y=205;y=wrap(ctx,currentDay.title,100,y,860,68);if(photo){const img=await loadImg(photo);const h=390;ctx.save();rounded(ctx,100,y+20,880,h,32);ctx.clip();drawCover(ctx,img,100,y+20,880,h);ctx.restore();y+=440}ctx.fillStyle='#5f5357';ctx.font='29px sans-serif';wrap(ctx,text,100,y+15,860,42);ctx.fillStyle='#a74e6c';ctx.font='bold 33px Georgia';ctx.fillText('Paris · Menton · alegem zilnic ❤️',100,1270);return await new Promise(r=>c.toBlob(r,'image/jpeg',.91))}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function drawCover(ctx,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),nw=img.width*s,nh=img.height*s;ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh)}function wrap(ctx,text,x,y,w,lh){for(const p of text.split('\n')){let line='';for(const word of p.split(' ')){if(ctx.measureText(line+word).width>w){ctx.fillText(line,x,y);y+=lh;line=''}line+=word+' '}ctx.fillText(line,x,y);y+=lh}return y}function loadImg(src){return new Promise(r=>{const i=new Image;i.onload=()=>r(i);i.src=src})}

function renderJourney(){renderHero();$('#app').innerHTML=`<div class="days-grid">${days.map(d=>`<button class="tile ${available(d)?'':'locked'}" data-day="${d.id}" ${available(d)?'':'disabled'}><b>Ziua ${d.id}</b><h3>${d.icon} ${esc(d.title)}</h3><small>${state.completed[d.id]?'✓ Sigilată':available(d)?'Disponibilă':'Se deschide la data ei'}</small></button>`).join('')}</div>`;$$('[data-day]').forEach(b=>b.onclick=()=>{currentDay=days.find(d=>d.id==b.dataset.day);stage=state.steps[currentDay.id]||0;renderHero();renderChapter()})}
function renderAlbum(){renderHero();const items=days.filter(d=>state.completed[d.id]);$('#app').innerHTML=items.length?`<div class="album-grid">${items.map(d=>`<div class="tile">${state.photos[d.id]?`<img src="${state.photos[d.id]}" alt="Ziua ${d.id}">`:`<div style="font-size:50px">${d.icon}</div>`}<b>Ziua ${d.id}</b><h3>${esc(d.title)}</h3><small>${esc(state.answers[d.id]?.text||state.answers[d.id]?.build||'Păstrată în poveste')}</small></div>`).join('')}</div>`:`<div class="panel"><h2>Albumul vostru începe cu primul plic sigilat</h2><p>Fotografiile rămân pe telefonul pe care au fost alese și intră în imaginea rezultatului.</p></div>`}
function renderTomorrow(){renderHero();const unread=state.tomorrow.filter(x=>x.openDate<=dateParis());$('#app').innerHTML=`<div class="panel tomorrow-box"><div class="kicker">DIN ASTĂZI PENTRU MÂINE</div><h2>Lasă ceva care merită așteptat</h2><p>Poate fi o întrebare, o încurajare, o rugăciune sau o mică surpriză. Linkul ajunge astăzi, dar conținutul se deschide la data de mâine.</p>${unread.map(l=>`<div class="sealed-letter"><b>💌 ${esc(l.fromName||'Plic primit')}</b><p>${esc(l.text)}</p></div>`).join('')}<div class="choices"><button class="choice selected" data-kind="Întrebare">Întrebare</button><button class="choice" data-kind="Gând">Gând</button><button class="choice" data-kind="Rugăciune">Rugăciune</button><button class="choice" data-kind="Surpriză">Surpriză</button></div><textarea id="tomorrowText" class="textarea" placeholder="Ce vrei să găsească mâine?"></textarea><button class="primary" id="sendTomorrow">Sigilează și trimite plicul ✉</button></div>`;let kind='Întrebare';$$('[data-kind]').forEach(b=>b.onclick=()=>{$$('[data-kind]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');kind=b.dataset.kind});$('#sendTomorrow').onclick=()=>{const text=$('#tomorrowText').value.trim();if(!text)return alert('Scrie mesajul pentru mâine.');const payload={id:crypto.randomUUID?.()||Date.now(),type:'letter',kind,text,openDate:dateParis(1),from:profile,fromName:me().name};const url=location.origin+location.pathname+'#letter='+encodeURIComponent(enc(payload));share({title:'Un plic pentru mâine',text:`Ți-am lăsat un plic pentru mâine 💌`,url})}}

init();
